ALTER TABLE `file_category` ADD `draft` BOOLEAN NOT NULL DEFAULT '0';
ALTER TABLE `file_category` ADD `link` VARCHAR( 255 ) NULL DEFAULT NULL ;

ALTER TABLE `file` ADD `draft` BOOLEAN NOT NULL DEFAULT '0';
ALTER TABLE `file` ADD `link` VARCHAR( 255 ) NULL DEFAULT NULL ;